apiVersion: v1
kind: Secret
metadata:
  name: healthcare-db-credentials
  namespace: healthcare
type: Opaque
data:
  # These values are base64 encoded
  # In a real scenario, you would never store these in version control
  # You can generate them with: echo -n "value" | base64
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
  database: cGF0aWVudGRi  # patientdb
  connection-string: cG9zdGdyZXNxbDovL2FkbWluOnBhc3N3b3JkMTIzQGhlYWx0aGNhcmUtZGI6NTQzMi9wYXRpZW50ZGI=  # postgresql://admin:password123@healthcare-db:5432/patientdb
---
apiVersion: v1
kind: Secret
metadata:
  name: healthcare-api-keys
  namespace: healthcare
type: Opaque
data:
  external-api-key: VGhpc0lzQVNlY3JldEFQSUtleQ==  # ThisIsASecretAPIKey
  encryption-key: U2VjdXJlRW5jcnlwdGlvbktleUZvckFwcGxpY2F0aW9uRGF0YQ==  # SecureEncryptionKeyForApplicationData
