apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-v2
  labels:
    app: web-app
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
      version: v2
  template:
    metadata:
      labels:
        app: web-app
        version: v2
    spec:
      containers:
        - name: web-app
          image: nginx:1.20
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: content-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content-volume
          configMap:
            name: web-content-v2
