apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content-v2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Web App - Version 2</title>
        <style>
            body {
                background-color: #2ecc71; /* Green background */
                color: white;
                font-family: Arial, sans-serif;
                text-align: center;
                padding-top: 100px;
            }
        </style>
    </head>
    <body>
      <h1>Version 2 (Green)</h1>
      <p>This is version 2 of our web application.</p>
      <p>We've added this new paragraph as a feature!</p>
    </body>
    </html>