apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
    version: v1  # Initially points to version 1 (blue)
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
