apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
    version: v2  # Now points to version 2 (green)
  ports:
    - port: 80
      targetPort: 80
  type: NodePort